services:
  app:
    container_name: otto-handler-app
    build:
      context: .
      target: development # 개발 스테이지 사용
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      - PORT=4000
    volumes:
      - .:/app # 소스코드 마운트
      - /app/node_modules # node_modules 제외
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    tty: false # 대화형 터미널 활성화
    stdin_open: false # 표준 입력 유지
    command: >
      sh -lc "pnpm install &&
              pnpm prisma generate &&
              pnpm run start:dev"

  postgres:
    container_name: otto-handler-postgres
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: otto_handler
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    container_name: otto-handler-redis
    image: redis:7.4-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
